### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by yamenchaban**
Profile page

### CODE REVIEW

**Review by pintermate225 — APPROVED** [review]
I think it's a great job

**Review by bela-riboczki-ext — CHANGES_REQUESTED** [review]
The front end code is awesome. But it is missing the back end.
We need to store the data about the user in the database and the user has to be able to change it using this page.

**Comment by yamenchaban** [comment]
I think we should create a new ticket in jira that contains the task of linking this page to the backend

**Comment by pintermate225** [comment]
Definetly

**Comment by bela-riboczki-ext** [comment]
As we talked about it, we created a new item for the back end.

**Review by bela-riboczki-ext — APPROVED** [review]

**Pull request merged**
